image: node:18

pipelines:
  default:
    - step:
        name: Build
        runs-on:
          - "self.hosted"
        script:
          - npm install
          - npm run build

definitions:
  runners:
    self.hosted: # nome do seu runner
      image: node:18 # a imagem Docker que seu runner vai usar
