version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: eichefe
      POSTGRES_PASSWORD: Lucas102030
      POSTGRES_DB: eichefedb
    ports:
      - 5432:5432
    networks:
      - eicheferede
    volumes:
      - eichefevolume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "eichefe", "-d", "eichefedb"]
      interval: 10s
      timeout: 5s
      retries: 3

  eichefeapizap:
    image: luuhsantanafs/eichefeapizap:1.0
    ports:
      - "8080:8080"
    networks:
      - eicheferede
    volumes:
      - eichefevolume:/app
    depends_on:
      - db      
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-s",
          "-o",
          "/dev/null",
          "-w",
          "%{http_code}",
          "http://localhost:8080",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management    
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - eicheferede
    environment:
      - RABBITMQ_DEFAULT_USER=luuhsantanafs
      - RABBITMQ_DEFAULT_PASS=Lucas102030
    volumes:
      - eichefevolume:/var/lib/rabbitmq
    depends_on:
      - db
      - lareanapizap
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3  

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiNzQyYzVkYTA5YjE2N2E4ZGU5OWMyZmI3ZjVjYzBkMDgiLCJ0IjoiMzFiNGIyOGItZGM3Ny00NmU1LWE1ZGQtNjAyYTM3MmZjN2ZjIiwicyI6IllXUXdZVEZpTlRRdFpUa3lNUzAwWkRnd0xUaG1Zamd0T1RReE5UWmxZelV4TlRVNCJ9
    networks:
      - eicheferede

volumes:
  eichefevolume:
     driver: local

networks:
  eicheferede:
    driver: overlay
