version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: eichefe
      POSTGRES_PASSWORD: Lucas102030
      POSTGRES_DB: eichefedb
    ports:
      - 5432:5432
    networks:
      - eicheferede
    volumes:
      - ./.Docker/db_data/db:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: always
    ports:
      - "9002:9000"
      - "9001:9001"
    command: server /data
    environment:
      MINIO_ACCESS_KEY: eichefe
      MINIO_SECRET_KEY: luuhsantanafs
    networks:
      - eicheferede
    volumes:
      - ./.Docker/minio_data/minio:/data
    depends_on:
      - db

  apizap:
    container_name: evolution_api
    image: atendai/evolution-api:homolog    
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./.Docker/evolution_instances:/evolution/instances
      - ./.Docker/evolution_store:/evolution/store
    networks:
      - eicheferede
    env_file:
      - ./configDocker/.env      
    command: ["node", "./dist/src/main.js"]
    expose:
      - 8080
    depends_on:
      - db
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:27017"]
      interval: 30s
      timeout: 10s
      retries: 5
    

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
    networks:
      - eicheferede
    environment:
      - RABBITMQ_DEFAULT_USER=luuhsantanafs
      - RABBITMQ_DEFAULT_PASS=Lucas102030
    volumes:
      - ./.Docker/eichefevolume/rabbitmq:/var/lib/rabbitmq
    depends_on:
      - db      

  

networks:
  eicheferede:
    driver: bridge
