version: "3.7"

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: eichefe
      POSTGRES_PASSWORD: Lucas102030
    volumes:
      - ./Docker/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - eicheferede
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

  minio:
    image: minio/minio
    volumes:
      - ./Docker/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data
    environment:
      MINIO_ACCESS_KEY: eichefe
      MINIO_SECRET_KEY: luuhsantanafs
    networks:
      - eicheferede
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

  lareanapizap:
    image: luuhsantanafs/lareanapizap:1.0
    volumes:
      - ./Docker/apiwhatsapp/instancia:/evolution/instances
      - ./Docker/apiwhatsapp/store:/evolution/store
    ports:
      - "8080:8080"
    networks:
      - eicheferede
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./Docker/rabbitmq/data:/var/lib/rabbitmq
    networks:
      - eicheferede
    environment:
      - RABBITMQ_DEFAULT_USER=luuhsantanafs
      - RABBITMQ_DEFAULT_PASS=Lucas102030
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  eicheferede:
    driver: overlay
