version: "3.7"

services:
  eichefe:    
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - target: 3000
          published: 3000
          protocol: http
          mode: host
      networks:
      - eicheferede
      volumes:
        - eichefevolume:/app
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure 
    

  db:
    image: postgres
    environment:
      POSTGRES_USER: eichefe
      POSTGRES_PASSWORD: Lucas102030
      POSTGRES_DB: eichefedb
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    networks:
      - eicheferede
    volumes:
      - eichefevolume:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  eichefeapizap:
    image: luuhsantanafs/eichefeapizap:1.0
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - eicheferede
    volumes:
      - eichefevolume:/app
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  rabbitmq:
    image: rabbitmq:3-management    
    ports:
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
    networks:
      - eicheferede
    environment:
      - RABBITMQ_DEFAULT_USER=luuhsantanafs
      - RABBITMQ_DEFAULT_PASS=Lucas102030
    volumes:
      - eichefevolume:/var/lib/rabbitmq
    depends_on:
      - db
      - lareanapizap
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiNzQyYzVkYTA5YjE2N2E4ZGU5OWMyZmI3ZjVjYzBkMDgiLCJ0IjoiMzFiNGIyOGItZGM3Ny00NmU1LWE1ZGQtNjAyYTM3MmZjN2ZjIiwicyI6IllXUXdZVEZpTlRRdFpUa3lNUzAwWkRnd0xUaG1Zamd0T1RReE5UWmxZelV4TlRVNCJ9
    networks:
      - eicheferede
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  eicheferede:
    driver: overlay
    external: true


volumes:
  eichefevolume:
     driver: local


