version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: eichefe
      POSTGRES_PASSWORD: Lucas102030
      POSTGRES_DB: eichefedb
    ports:
      - 5432:5432
    networks:
      - eicheferede
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        
  minio:
    image: minio/minio
    ports:
      - "9002:9000"
      - "9001:9001"
    command: server /data
    environment:
      MINIO_ACCESS_KEY: eichefe
      MINIO_SECRET_KEY: luuhsantanafs
    networks:
      - eicheferede
    volumes:
      - minio_data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db

  lareanapizap:
    image: luuhsantanafs/lareanapizap:1.0
    ports:
      - "8080:8080"
    networks:
      - eicheferede
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - apizap_data:/app
    depends_on:
      - db
      - minio

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - eicheferede
    environment:
      - RABBITMQ_DEFAULT_USER=luuhsantanafs
      - RABBITMQ_DEFAULT_PASS=Lucas102030
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    depends_on:
      - db
      - minio
      - lareanapizap

networks:
  eicheferede:
    driver: overlay
    attachable: true

volumes:
  minio_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.71,nfsvers=4,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: :/mnt/volumenfs
  db_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.71,nfsvers=4,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: :/mnt/volumenfs
  apizap_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.71,nfsvers=4,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: :/mnt/volumenfs
  rabbitmq_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.71,nfsvers=4,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: :/mnt/volumenfs
    
    